from tkinter import*
window=Tk()
window.title("sample window")
window.geometry('500x300')
greetings=Label(text="hello user",fg="black",bg="white")
button=Button(text="click me",bg="black",fg="white")
entry=Entry(fg="yellow",bg="blue",width=50)
greetings.pack()
button.pack()
entry.pack()
frame=Frame(master=window,relief=RAISED,borderwidth=5)
frame.pack()
label=Label(master=frame,text="mini frame")
label.pack()
textbox=Text(fg="green",bg="red")
textbox.pack()
window.mainloop()